version: '2.19.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  fastapi: 
    build: ./backend/pdf
    command:  uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/pdf:/app
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - zookeeper

  textcleaner: 
    build: ./backend/textCleaner
    command:  python3 main.py
    volumes:
      - ./backend/textCleaner:/app
    ports:
      - 8001:8000
    depends_on:
      - kafka
      - zookeeper
      - fastapi

  frontend:
    build:
      context: ./frontend/cvizard
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    depends_on:
      - kafka
    container_name: frontend
