server:
  port: 443
  ssl:
    enabled: true
    key-alias: minionki
    key-store-password:
    key-store: classpath:scg-minionki.p12
    key-store-type: PKCS12
    trust-store: classpath:keystore/minionki.p12
    trust-store-password: 

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: pdf
          uri: http://localhost:8081